---
  - name: Laravel Dev Configuration with Ansible
    hosts: all
    sudo: True
    vars:
        #
        # document root option for the virtualhost template
        #
        document_root: /vagrant/NAME_OF_THE_PROJECT/public
        #
        # you can choose btw mysql or mongodb
        #
        db: TYPE_DB
        #
        # the following option will be considered only if TYPE_DB = mysql
        #
        db_name: NAME_OF_DB_PROJECT
    pre_tasks:
      - name: update apt cache
        apt: update_cache=yes
    roles:
      - database
      - webserver
      - common
