---
- name: install php
  apt: pkg={{ item }} state=installed
  with_items:
    - php-fpm
    - php-cli
    - php-common
    - php-curl
    - php-json
    - php-pear
    - php-gd
    - mcrypt
    - php-mcrypt
    - php-mysql
    - php-sqlite
    - php-xmlrpc
    - libapache2-mod-php
    - php-ldap
- name: install phpMyAdmin
  apt: pkg={{ item }} state=present
  with_items:
    - phpmyadmin
    - libmysqlclient-dev
- name: Ensure PHPMyAdmin config file is included in Apache config.
  lineinfile: >
    dest=/etc/apache2/apache2.conf
    state=present
    regexp="^Include.+phpmyadmin.+$"
    line="Include /etc/phpmyadmin/apache.conf"
    insertafter="EOF"
  notify:
    - reload apache
- name: Add default username and password for MySQL connection.
  lineinfile: >
    dest=/etc/phpmyadmin/config.inc.php
    state=present
    regexp="^.+\['{{ item.key }}'\].+$"
    line="$cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
  with_items:
    - { key: user, value: "root" }
    - { key: password, value: "root"}
  notify:
    - reload apache
